[tool.poetry]
name = "project2"
version = "0.1.0"
description = ""
authors = ["lppavli <lp.pavli@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
flask = "^2.3.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
